version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    ports:
      - '27017:27017'
    volumes:
      - type: bind
        source: ./mongoData
        target: /data/db

volumes:
  mongoData:
